version: '3.9'
services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379

  redis-cli:
    image: redis:latest
    depends_on:
      - redis
    entrypoint: redis-cli
    command: -h redis
